<?php

namespace ShopBundle\Repository;

/**
 * UserShopPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserShopPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
