shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /api

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /doc
app:
    resource: '@AppBundle/Controller/'
    type: annotation
