services:
        shop.authenticator:
                    class: ShopBundle\Security\TokenAuthenticator
                    autowire: true
        shop.user_provider:
                    class: ShopBundle\Security\UserProvider
                    arguments: [ "@doctrine.orm.entity_manager"]
        shop.request:
                    class: ShopBundle\Services\RequestService
        shop.user:
                    class: ShopBundle\Services\UserService
                    arguments: ["@service_container"]
        shop.response:
                    class: ShopBundle\Services\ResponseService
        shop.jwt:
                    class: ShopBundle\Security\JsonWebToken
                    arguments: [ "@service_container"]