services:
        shop.authenticator:
                    class: ShopBundle\Security\TokenAuthenticator
                    autowire: true
        shop.user_provider:
                    class: ShopBundle\Security\UserProvider
                    arguments: [ "@doctrine.orm.entity_manager"]
        shop.request:
                    class: ShopBundle\Services\RequestService
        shop.user:
                    class: ShopBundle\Services\UserService
                    arguments: ["@service_container"]
        shop.response:
                    class: ShopBundle\Services\ResponseService
        shop.jwt:
                    class: ShopBundle\Security\JsonWebToken
                    arguments: [ "@service_container"]
        shop.shop:
                    class: ShopBundle\Services\ShopService
                    arguments: [ "@doctrine.orm.entity_manager","@service_container"]
        kernel.listener.updateHeader:
                    class: ShopBundle\Services\RequestListener
                    tags:
                    - { name: kernel.event_listener, event: kernel.request ,method: onKernelRequest , priority: 300 }
                    - { name: kernel.event_listener, event: kernel.response ,method: onKernelResponse }

